/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClientAccess;
import co.unicauca.microkernel.client.domain.ClientService;
import co.unicauca.microkernel.common.entities.Pedido;
import co.unicauca.microkernel.common.entities.Restaurant;
import co.unicauca.microkernel.plugin.restaurant.Tabla_Restaurantes;
import co.unicauca.restaurant.client.hexagonal.plugin.pedido.Tabla_Pedidos;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author braia
 */
public class GUIListarPedidos extends javax.swing.JFrame {
    IClientAccess service;
    private List<Pedido> listaPedidos = null;
    private String usuario = "";
    /**
     * Creates new form GUIListarPedidos
     */
    public GUIListarPedidos() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        this.service = Factory.getInstance().getClienteService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        pnlListarPed = new javax.swing.JPanel();
        LblAplicacion = new javax.swing.JLabel();
        LblListarPedidos = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();
        LblTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnListarPedido = new javax.swing.JButton();

        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("Software Food");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlListarPed.setBackground(new java.awt.Color(0, 0, 0));

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblListarPedidos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblListarPedidos.setForeground(new java.awt.Color(255, 255, 255));
        LblListarPedidos.setText("Listar Pedidos");

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        lblImgPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblImgPrincipal.setText("ImgPrincipal");

        LblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo1.setText("Software Food");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(tblPedidos);

        btnListarPedido.setText("Listar Pedidos");
        btnListarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListarPedLayout = new javax.swing.GroupLayout(pnlListarPed);
        pnlListarPed.setLayout(pnlListarPedLayout);
        pnlListarPedLayout.setHorizontalGroup(
            pnlListarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarPedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAtras)
                .addGap(41, 41, 41))
            .addGroup(pnlListarPedLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblImgPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(LblAplicacion)
                .addGap(284, 284, 284))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarPedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarPedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblListarPedidos)
                .addGap(356, 356, 356))
            .addGroup(pnlListarPedLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(btnListarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListarPedLayout.setVerticalGroup(
            pnlListarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarPedLayout.createSequentialGroup()
                .addGroup(pnlListarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListarPedLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BtnAtras))
                    .addGroup(pnlListarPedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitulo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAplicacion)
                    .addComponent(lblImgPrincipal))
                .addGap(18, 18, 18)
                .addComponent(LblListarPedidos)
                .addGap(55, 55, 55)
                .addComponent(btnListarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListarPed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListarPed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUIOpcionesAdmin ins = new GUIOpcionesAdmin();
        ins.getUsuario(usuario);
        ins.nombreAdmin(usuario);
        ins.setVisible(true);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void btnListarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPedidoActionPerformed
        try {
            listarPedido();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarPedidos().setVisible(true);
            }
        });
    }
    
    private void showImage() {
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
        pnlListarPed.add(lblImgPrincipal);
    }
    
    public void listarPedido() throws Exception {
        ClientService servicioRestaurante = new ClientService(service);
        List<Pedido> lsPedido = servicioRestaurante.listarPedido();

        this.AllPedidos = lsPedido;
        
        System.out.println("TAMAÑO PEDIDOS: "+ AllPedidos.size());
        
        if (AllPedidos.size() > 0) {
            this.MostrarTabla(this.pedidos_Admin());
        }
    }
    
    private List<Pedido> AllPedidos = null;
    
    public List<Pedido> GetPedidos() {
        try {
            listarPedido();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return AllPedidos;
    }
    
    public void MostrarTabla(List<Pedido> pedidos) {
        System.out.println("ENTRO A MOSTRAR TABLA PEDIDOS-----------");
        Tabla_Pedidos tabla = new Tabla_Pedidos();
        tabla.visualizar_Pedido(tblPedidos, pedidos); 
    }
    
   private void listarPedidos() throws Exception{
       ClientService servicioRestaurante = new ClientService(service);              
        listaPedidos =  servicioRestaurante.listarPedido();
   }
   private int obtnerRestaurantes_Nit() throws Exception{
       List<Restaurant> restaurantes = null;
       ClientService servicioRestaurante = new ClientService(service);              
        restaurantes =  servicioRestaurante.listarRestaurants();
        
        for (int i = 0; i < restaurantes.size(); i++) {
           if(restaurantes.get(i).getCli_Id().getCus_id() == Integer.valueOf(this.usuario)){
               return restaurantes.get(i).getNit();
           }
       }
        return -1;
   }
   private List<Pedido> pedidos_Admin(){
       int res_Nit = -1;
       List<Pedido> pedidos = new ArrayList<Pedido>();
        try {
            res_Nit = this.obtnerRestaurantes_Nit();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
       
       for (int i = 0; i < this.AllPedidos.size(); i++) {
            if(this.AllPedidos.get(i).getRes_Nit() == res_Nit){
                pedidos.add(AllPedidos.get(i));
            }
       }
      return pedidos;
   }
   public void setUsuario(String usuario){
        this.usuario = usuario;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblListarPedidos;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JButton btnListarPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JPanel pnlListarPed;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
