/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClientAccess;
import co.unicauca.microkernel.client.domain.ClientService;
import co.unicauca.microkernel.common.entities.Restaurant;
import co.unicauca.microkernel.plugin.restaurant.Tabla_Restaurantes;
import java.awt.event.ActionEvent;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author juan jose
 */
public class GUIListarRestaurantes extends javax.swing.JFrame {

    private String usuario = "";
    private int posicionClick;
    private String nomRest = "";
    private String IDCliente = "";
    IClientAccess service;
    DefaultListModel modelListCoRestaurantes;

    /**
     * Creates new form GUIListarRestaurantes
     */
    public GUIListarRestaurantes() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        this.modelListCoRestaurantes = new DefaultListModel();
        this.service = Factory.getInstance().getClienteService();
        this.posicionClick = -1;
        btnSelecRestaurat.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListComponentes = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PnlListarRestaurantes = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblVerRestaurantes = new javax.swing.JLabel();
        BtnVerRestaurantes = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        btnSelecRestaurat = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDUsuario = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRestaurants = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlListarRestaurantes.setBackground(new java.awt.Color(0, 0, 0));

        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblVerRestaurantes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblVerRestaurantes.setForeground(new java.awt.Color(255, 255, 255));
        LblVerRestaurantes.setText("Visualizar los restaurantes que tiene la ciudad");

        BtnVerRestaurantes.setText("Visualizar Restaurantes");
        BtnVerRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerRestaurantesActionPerformed(evt);
            }
        });

        BtnAtras.setText("Cerrar sesión");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        btnSelecRestaurat.setText("Seleccionar Restaurante");
        btnSelecRestaurat.setName("btnSelecRestaurat"); // NOI18N
        btnSelecRestaurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecRestauratActionPerformed(evt);
            }
        });

        lblImgPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblImgPrincipal.setText("ImgPrincipal");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID del Cliente:");

        txtIDUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtIDUsuario.setText("----------------");
        txtIDUsuario.setToolTipText("");

        tblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRestaurants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRestaurantsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblRestaurants);

        javax.swing.GroupLayout PnlListarRestaurantesLayout = new javax.swing.GroupLayout(PnlListarRestaurantes);
        PnlListarRestaurantes.setLayout(PnlListarRestaurantesLayout);
        PnlListarRestaurantesLayout.setHorizontalGroup(
            PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAtras))
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblImgPrincipal)
                                .addGap(102, 102, 102)
                                .addComponent(LblAplicacion))
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblVerRestaurantes)
                                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(BtnVerRestaurantes))
                            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnSelecRestaurat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlListarRestaurantesLayout.setVerticalGroup(
            PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitulo)
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImgPrincipal)
                            .addComponent(LblAplicacion)))
                    .addGroup(PnlListarRestaurantesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)))
                .addGap(25, 25, 25)
                .addComponent(LblVerRestaurantes)
                .addGap(19, 19, 19)
                .addGroup(PnlListarRestaurantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVerRestaurantes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnSelecRestaurat)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        BtnAtras.getAccessibleContext().setAccessibleDescription("");
        txtIDUsuario.getAccessibleContext().setAccessibleName("");

        getContentPane().add(PnlListarRestaurantes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecRestauratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecRestauratActionPerformed
        // TODO add your handling code here:
        setVisible(false);

//        System.out.println("Valor2" + btnSelecRestaurat.getText());
        //if(BtnVerRestaurantes.isSelected() && tblRestaurants.getColumnSelectionAllowed()){
        this.jTableMouseClicked();
        //}
        System.out.println("Valor10: " + this.nomRest);
        GUISeleccionarRestaurante ins = new GUISeleccionarRestaurante(this.nomRest);
        ins.setIDCliente(usuario);
        ins.setVisible(true);

//        ins.nombreRestaurante(this.nomRest);

    }//GEN-LAST:event_btnSelecRestauratActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUILoginCliente ins = new GUILoginCliente();
        ins.setVisible(true);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnVerRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerRestaurantesActionPerformed
        txtIDUsuario.removeAll();
        txtIDUsuario.setText(usuario);
        try {
            listar();
//            btnSelecRestaurat.setEnabled(true);
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnVerRestaurantesActionPerformed

    private void tblRestaurantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRestaurantsMouseClicked
       
        btnSelecRestaurat.setEnabled(true);

    }//GEN-LAST:event_tblRestaurantsMouseClicked

    public void listar() throws Exception {
        ClientService servicioRestaurante = new ClientService(service);
        List<Restaurant> lsRestaurante = servicioRestaurante.listarRestaurants();
        this.AllRestaurants = lsRestaurante;

        if (lsRestaurante.size() > 0) {
            this.MostrarTabla(lsRestaurante);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarRestaurantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarRestaurantes().setVisible(true);
            }
        });
    }

    private List<Restaurant> AllRestaurants = null;

    public List<Restaurant> GetRestaurants() {
        try {
            listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
        return AllRestaurants;
    }

    private void showImage() {

        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
        PnlListarRestaurantes.add(lblImgPrincipal);

    }

    public void getUsuario(String usuario) {
        this.usuario = usuario;
    }

    public void MostrarTabla(List<Restaurant> restaurantes) {
        System.out.println("ENTRO A MOSTRAR TABLA -----------");
        Tabla_Restaurantes tabla = new Tabla_Restaurantes();
        tabla.visualizar_Restaurante(tblRestaurants, restaurantes);
    }

    private void jTableMouseClicked() {
        this.posicionClick = tblRestaurants.getSelectedRow();
        this.nomRest = String.valueOf(tblRestaurants.getValueAt(posicionClick, 1));
//           btnSelecRestaurat.setText(String.valueOf(tblRestaurants.getValueAt(posicionClick, 1)));
//          System.out.println("Valor: " + String.valueOf(tblRestaurants.getValueAt(posicionClick, 1)));

        System.out.println("Valor: " + this.nomRest);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnVerRestaurantes;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblVerRestaurantes;
    private javax.swing.JList<String> ListComponentes;
    private javax.swing.JPanel PnlListarRestaurantes;
    private javax.swing.JButton btnSelecRestaurat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JTable tblRestaurants;
    private javax.swing.JLabel txtIDUsuario;
    // End of variables declaration//GEN-END:variables
}
