/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;


import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClientAccess;
import co.unicauca.microkernel.client.domain.ClientService;
import co.unicauca.microkernel.common.entities.Component;
import co.unicauca.microkernel.plugin.componente.Tabla_Componentes;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author juan jose
 */
public class GUIListarComponentes extends javax.swing.JFrame {

    IClientAccess service;
    
    DefaultListModel modelListComponentes;
    private String usuario ="";
    
    /**
     * Creates new form GUIListarComponentes
     */
    public GUIListarComponentes() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        this.modelListComponentes = new DefaultListModel();
        this.service = Factory.getInstance().getClienteService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlListarComponentes = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblListarComponentes = new javax.swing.JLabel();
        BtnListarComponentes = new javax.swing.JButton();
        BtnAtras = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComponents = new javax.swing.JTable();
        btnAgregarComp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlListarComponentes.setBackground(new java.awt.Color(0, 0, 0));

        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        LblListarComponentes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblListarComponentes.setForeground(new java.awt.Color(255, 255, 255));
        LblListarComponentes.setText("Listar Componentes Almuerzo Ejecutivo");

        BtnListarComponentes.setText("Listar componentes");
        BtnListarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarComponentesActionPerformed(evt);
            }
        });

        BtnAtras.setText("Atrás");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        lblImgPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblImgPrincipal.setText("ImgPrincipal");

        tblComponents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblComponents);

        btnAgregarComp.setText("Agregar Componente");
        btnAgregarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlListarComponentesLayout = new javax.swing.GroupLayout(PnlListarComponentes);
        PnlListarComponentes.setLayout(PnlListarComponentesLayout);
        PnlListarComponentesLayout.setHorizontalGroup(
            PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlListarComponentesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlListarComponentesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblImgPrincipal))
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addContainerGap(571, Short.MAX_VALUE)
                        .addComponent(BtnAtras)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblAplicacion)
                            .addComponent(LblListarComponentes)))
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(BtnListarComponentes)
                        .addGap(93, 93, 93)
                        .addComponent(btnAgregarComp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlListarComponentesLayout.setVerticalGroup(
            PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblImgPrincipal)
                        .addGap(33, 33, 33))
                    .addGroup(PnlListarComponentesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblAplicacion)
                        .addGap(18, 18, 18)))
                .addComponent(LblListarComponentes)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PnlListarComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnListarComponentes)
                    .addComponent(btnAgregarComp))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(PnlListarComponentes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        setVisible(false);
        GUIOpcionesAdmin ins = new GUIOpcionesAdmin();
        ins.getUsuario(usuario);
        ins.nombreAdmin(usuario);
        ins.setVisible(true); 
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnListarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarComponentesActionPerformed
        try {
            listar();           
        } catch (Exception ex) {
            Logger.getLogger(GUIListarComponentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnListarComponentesActionPerformed

    private void btnAgregarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompActionPerformed
        setVisible(false);
        GUIAgregarComponentes agg = new GUIAgregarComponentes();
        agg.setUsuario(usuario);
        agg.setVisible(true);
    }//GEN-LAST:event_btnAgregarCompActionPerformed
    
    
    public void listar() throws Exception {
        ClientService servicioRestaurante = new ClientService(service);
        List<Component> lsComponente = servicioRestaurante.listarComponents();
        if (lsComponente.size() > 0) {           
            this.MostrarTabla(lsComponente);
        }
    }
    
    private void showImage() {
        
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80,Image.SCALE_SMOOTH)));
        PnlListarComponentes.add(lblImgPrincipal);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIListarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIListarComponentes().setVisible(true);
            }
        });
    }
    
    public void MostrarTabla(List<Component> componentes) {
        System.out.println("ENTRO A MOSTRAR TABLA -----------");
        Tabla_Componentes tabla = new Tabla_Componentes();
        tabla.visualizar_Componente(tblComponents, componentes);
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnListarComponentes;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblListarComponentes;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlListarComponentes;
    private javax.swing.JButton btnAgregarComp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JTable tblComponents;
    // End of variables declaration//GEN-END:variables
}
