/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.Factory;
import co.unicauca.microkernel.client.access.IClientAccess;
import co.unicauca.microkernel.client.domain.ClientService;
import co.unicauca.microkernel.common.entities.Customer;
import co.unicauca.microkernel.common.entities.Restaurant;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author juan jose
 */
public class GUIOpcionesAdmin extends javax.swing.JFrame {
    private String usuario = "";
    private String nom_Usuario = "";
    private String nom_Restaurant="";
    IClientAccess service;
    ClientService servicioRestaurante;
    /**
     * Creates new form GUIOpcionesAdmin
     */
    public GUIOpcionesAdmin() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        service = Factory.getInstance().getClienteService();
        servicioRestaurante = new ClientService(service);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlOpcionesAdmin = new javax.swing.JPanel();
        LblTitulo = new javax.swing.JLabel();
        LblAplicacion = new javax.swing.JLabel();
        LblIngresaste = new javax.swing.JLabel();
        LblSelecionaOpcion = new javax.swing.JLabel();
        BtnAgregarComponentes = new javax.swing.JButton();
        BtnListarComponentes = new javax.swing.JButton();
        BtnActualizarAlmuezo = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();
        btnListarPedidos = new javax.swing.JButton();
        lblNomRestaurante = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblNomUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlOpcionesAdmin.setBackground(new java.awt.Color(0, 0, 0));

        LblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LblTitulo.setText("Software Food");

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("   Aplicación Software Food");

        LblIngresaste.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblIngresaste.setForeground(new java.awt.Color(255, 255, 255));
        LblIngresaste.setText("Ingresaste como Administrador");

        LblSelecionaOpcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LblSelecionaOpcion.setForeground(new java.awt.Color(255, 255, 255));
        LblSelecionaOpcion.setText("Seleccione lo que desea realizar");

        BtnAgregarComponentes.setText("Agregar componentes almuerzo ejecutivo");
        BtnAgregarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarComponentesActionPerformed(evt);
            }
        });

        BtnListarComponentes.setText("Listar Componentes almuerzo ejecutivo");
        BtnListarComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarComponentesActionPerformed(evt);
            }
        });

        BtnActualizarAlmuezo.setText("Actualizar almuerzo ejecutivo del día");
        BtnActualizarAlmuezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarAlmuezoActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        lblImgPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblImgPrincipal.setText("ImgPrincipal");

        btnListarPedidos.setText("Listar Pedidos");
        btnListarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPedidosActionPerformed(evt);
            }
        });

        lblNomRestaurante.setBackground(new java.awt.Color(0, 0, 0));
        lblNomRestaurante.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblNomRestaurante.setForeground(new java.awt.Color(255, 255, 255));
        lblNomRestaurante.setText(" Restaurante");
        lblNomRestaurante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");

        lblNomUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblNomUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblNomUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNomUsuario.setText("Nombre Usuario");
        lblNomUsuario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante:");

        javax.swing.GroupLayout PnlOpcionesAdminLayout = new javax.swing.GroupLayout(PnlOpcionesAdmin);
        PnlOpcionesAdmin.setLayout(PnlOpcionesAdminLayout);
        PnlOpcionesAdminLayout.setHorizontalGroup(
            PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlOpcionesAdminLayout.createSequentialGroup()
                .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuario)
                            .addComponent(jLabel1)))
                    .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblImgPrincipal)
                        .addGap(245, 245, 245)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblIngresaste)
                        .addComponent(LblSelecionaOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnAgregarComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnListarComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(BtnActualizarAlmuezo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlOpcionesAdminLayout.setVerticalGroup(
            PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                        .addComponent(LblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblImgPrincipal))
                    .addGroup(PnlOpcionesAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomUsuario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(PnlOpcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomRestaurante)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(LblAplicacion)
                .addGap(18, 18, 18)
                .addComponent(LblIngresaste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblSelecionaOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgregarComponentes)
                .addGap(18, 18, 18)
                .addComponent(BtnListarComponentes)
                .addGap(18, 18, 18)
                .addComponent(BtnActualizarAlmuezo)
                .addGap(18, 18, 18)
                .addComponent(btnListarPedidos)
                .addGap(100, 100, 100))
        );

        lblNomRestaurante.getAccessibleContext().setAccessibleName("jlabel");

        getContentPane().add(PnlOpcionesAdmin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarComponentesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GUIAgregarComponentes ins = new GUIAgregarComponentes();
        ins.setUsuario(usuario);
        ins.setVisible(true); 
    }//GEN-LAST:event_BtnAgregarComponentesActionPerformed

    private void BtnActualizarAlmuezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarAlmuezoActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GUIActualizarAlmuerzo ins = new GUIActualizarAlmuerzo();
        ins.setUsuario(usuario);
        ins.setVisible(true);
    }//GEN-LAST:event_BtnActualizarAlmuezoActionPerformed

    private void BtnListarComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarComponentesActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        GUIListarComponentes ins = new GUIListarComponentes();
        ins.setUsuario(usuario);
        ins.setVisible(true);
    }//GEN-LAST:event_BtnListarComponentesActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        setVisible(false);
        GUILoginAdmin ins = new GUILoginAdmin();
        ins.setVisible(true); 
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void btnListarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPedidosActionPerformed
        setVisible(false);
        GUIListarPedidos ins = new GUIListarPedidos();
        ins.setUsuario(usuario);
        ins.setVisible(true);
    }//GEN-LAST:event_btnListarPedidosActionPerformed
    
    private void showImage() {
        
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80,Image.SCALE_SMOOTH)));
        PnlOpcionesAdmin.add(lblImgPrincipal);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOpcionesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOpcionesAdmin().setVisible(true);
                
            }
        });
    }
    
    public void getUsuario(String usuario){
        this.usuario = usuario;
        System.out.println("Usuario: " + usuario + "---");
    }
    
    public  void nombreAdmin(String usuario){
        System.out.println("usuario----admin: " +usuario);
        List<Customer> clientes = null;
        List<Restaurant> restaurantes = null;
        try {
            clientes = servicioRestaurante.findCustomer();
            restaurantes = servicioRestaurante.listarRestaurants();            
        } catch (Exception e) {
            System.out.println("Problemas al usar los servicios del cliente");
        }
         System.out.println("usuario: " + usuario);
        for (int i = 0; i < clientes.size(); i++) {
            if(Integer.valueOf(usuario) == clientes.get(i).getCus_id()){
                nom_Usuario = clientes.get(i).getCus_nombre();                
                nombreRestaurant(restaurantes, usuario);
            }
        }
        System.out.println("Nombre usuario: " + nom_Usuario);
        
    }
    private void nombreRestaurant(List<Restaurant> restaurantes, String usuario){
        for (int i = 0; i < restaurantes.size(); i++) {
            if(String.valueOf(restaurantes.get(i).getCli_Id().getCus_id()).equals(usuario)){
                nom_Restaurant = restaurantes.get(i).getNombre();
                System.out.println("Nombre restaurante: " + nom_Restaurant);
            }
        }
        System.out.println("Nombre restaurante: " + nom_Restaurant);
        mostrarDatos();
    }
    private void mostrarDatos(){
        this.lblNomUsuario.setText(nom_Usuario);
//        this.lblNomUsuario.setBackground(Color.ORANGE);
//        this.lblNomUsuario.setForeground(Color.white);
        this.lblNomRestaurante.setText(nom_Restaurant);
//        this.lblNomRestaurante.setBackground(Color.black);
//        this.lblNomRestaurante.setForeground(Color.white);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarAlmuezo;
    private javax.swing.JButton BtnAgregarComponentes;
    private javax.swing.JButton BtnListarComponentes;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JLabel LblIngresaste;
    private javax.swing.JLabel LblSelecionaOpcion;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel PnlOpcionesAdmin;
    private javax.swing.JButton btnListarPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JLabel lblNomRestaurante;
    private javax.swing.JLabel lblNomUsuario;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
