/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.client.access.ClientAccessSocket;
import co.unicauca.microkernel.client.access.IClientAccess;
import co.unicauca.microkernel.client.domain.ClientService;
import co.unicauca.microkernel.common.entities.Component;
import co.unicauca.microkernel.common.entities.PedEstado;
import co.unicauca.microkernel.common.entities.Pedido;
import co.unicauca.microkernel.common.entities.PlatoEjecutivo;
import co.unicauca.microkernel.common.entities.Restaurant;
import co.unicauca.microkernel.common.infra.Utilities;
import co.unicauca.microkernel.plugin.componente.Tabla_Componentes;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author braia
 */
public final class GUIRealizarPedido extends javax.swing.JFrame {

    private PlatoEjecutivo plato;
    private List<Component> ListaComponentes;
    private Restaurant restaurante;
    private String IDCliente = "";
    private int cantidad;

    /**
     * Creates new form GUIRealizarPedido
     */
    public GUIRealizarPedido() {
        initComponents();
        showImage();
        this.setLocationRelativeTo(null);
        btnRealizarPed.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblAplicacion = new javax.swing.JLabel();
        pnlRealizarPed = new javax.swing.JPanel();
        lblSf = new javax.swing.JLabel();
        lblMensAplicacion = new javax.swing.JLabel();
        lblRePed = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLableIMGPlato = new javax.swing.JLabel();
        btnRealizarPed = new javax.swing.JButton();
        lblImgPrincipal = new javax.swing.JLabel();

        LblAplicacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        LblAplicacion.setText("Aplicación Software Food");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRealizarPed.setBackground(new java.awt.Color(0, 0, 0));

        lblSf.setBackground(new java.awt.Color(0, 0, 0));
        lblSf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSf.setForeground(new java.awt.Color(255, 255, 255));
        lblSf.setText("Aplicación Software Food");

        lblMensAplicacion.setForeground(new java.awt.Color(255, 255, 255));
        lblMensAplicacion.setText("software food");

        lblRePed.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblRePed.setForeground(new java.awt.Color(255, 255, 255));
        lblRePed.setText("Realizar Pedido");

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad a Pedir : ");

        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });

        btnRealizarPed.setText("Realizar Pedido");
        btnRealizarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedActionPerformed(evt);
            }
        });

        lblImgPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblImgPrincipal.setText("imgPrincipal");

        javax.swing.GroupLayout pnlRealizarPedLayout = new javax.swing.GroupLayout(pnlRealizarPed);
        pnlRealizarPed.setLayout(pnlRealizarPedLayout);
        pnlRealizarPedLayout.setHorizontalGroup(
            pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                        .addComponent(lblMensAplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnRealizarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
            .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblImgPrincipal)
                .addGap(179, 179, 179)
                .addComponent(lblSf, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRealizarPedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRealizarPedLayout.createSequentialGroup()
                        .addComponent(lblRePed, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRealizarPedLayout.createSequentialGroup()
                        .addComponent(jLableIMGPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );
        pnlRealizarPedLayout.setVerticalGroup(
            pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                .addGroup(pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                        .addComponent(lblMensAplicacion)
                        .addGap(10, 10, 10)
                        .addGroup(pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras)))
                    .addGroup(pnlRealizarPedLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblImgPrincipal)))
                .addGap(18, 18, 18)
                .addComponent(lblRePed)
                .addGap(56, 56, 56)
                .addComponent(jLableIMGPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnlRealizarPedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRealizarPed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRealizarPed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        setVisible(false);
        GUIListarRestaurantes ins = new GUIListarRestaurantes();
        ins.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRealizarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedActionPerformed

        if ((txtCantidad.getText().length() > 0) && (Utilities.isNumeric(txtCantidad.getText()) && Integer.valueOf(txtCantidad.getText()) > 0)) {
            int total = 0;
            cantidad = Integer.valueOf(txtCantidad.getText());
            total = (this.plato.getPrecio()) * cantidad;

            int confirmado = JOptionPane.showConfirmDialog(null, "El valor total a Pagar es: " + total + "\n ¿Desea Continuar?", "Confirmar Pedido", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);;
            if (JOptionPane.OK_OPTION == confirmado) {
                int ID_ped = 0;
                try {
                    ID_ped = tamanioPed() + 1;
                } catch (Exception ex) {
                    Logger.getLogger(GUIRealizarPedido.class.getName()).log(Level.SEVERE, null, ex);
                }

                Calendar fecha = new GregorianCalendar();
                int año = fecha.get(Calendar.YEAR);
                int mes = fecha.get(Calendar.MONTH);
                int dia = fecha.get(Calendar.DAY_OF_MONTH);
                int hora = fecha.get(Calendar.HOUR_OF_DAY);
                int minuto = fecha.get(Calendar.MINUTE);

                String fecha_ped = (dia + "/" + (mes + 1) + "/" + año);
                String hora_ped = (hora + ":" + minuto);

                addPedido(ID_ped, Integer.valueOf(IDCliente), plato.getResNIT(), plato, cantidad, fecha_ped, hora_ped, PedEstado.CREADO, total);
               
            } else {
                JOptionPane.showMessageDialog(null, "Pedido Cancelado");
                
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe Digitar Una Cantidad Válida");
            
        }


    }//GEN-LAST:event_btnRealizarPedActionPerformed

    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        btnRealizarPed.setEnabled(true);
    }//GEN-LAST:event_txtCantidadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GUIRealizarPedido().setVisible(true);
            }
        });
    }

    void recibirPlato(PlatoEjecutivo plato) {
        this.plato = plato;
    }

    public void setIDCliente(String ID) {
        this.IDCliente = ID;
    }

    public void imgPedido(PlatoEjecutivo plato) {
        System.out.println("IMAGENNN" + plato.getFoto().toString());
        BufferedImage image = null;
        InputStream in = new ByteArrayInputStream(plato.getFoto());
        try {
            image = ImageIO.read(in);
        } catch (IOException ex) {
            Logger.getLogger(GUIRealizarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon imgi = new ImageIcon(image.getScaledInstance(314, 314, 0));
        jLableIMGPlato.setIcon(imgi);
        jLableIMGPlato.setHorizontalAlignment(jLableIMGPlato.CENTER);
        jLableIMGPlato.setVerticalAlignment(jLableIMGPlato.CENTER);
    }

    private void showImage() {
        ImageIcon imagen = new ImageIcon("imagen_softwareFood.jpeg");
        lblImgPrincipal.setBounds(10, 15, 80, 80);
        lblImgPrincipal.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH)));
        pnlRealizarPed.add(lblImgPrincipal);
    }

    private void addPedido(int ped_Id, int cli_Id, int res_Nit, PlatoEjecutivo plaEje_Dia, int ped_Cantidad, String ped_fecha, String ped_Hora, PedEstado ped_Estado, int ped_PrecioTotal) {
        IClientAccess service = new ClientAccessSocket();
        ClientService cliente = new ClientService(service);

        Pedido pedido = new Pedido(ped_Id, cli_Id, res_Nit, plaEje_Dia, ped_Cantidad, ped_fecha, ped_Hora, ped_Estado, ped_PrecioTotal);

        try {
            String resultComponent = service.savePedido(pedido);
            System.out.println(resultComponent);
            JOptionPane.showMessageDialog(null, "Pedido Realizado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El Pedido Ingresado ya esta registrado" + e.getMessage());
        }
    }

    private int tamanioPed() throws Exception {
        IClientAccess service = new ClientAccessSocket();
        ClientService servicioRestaurante = new ClientService(service);
        List<Pedido> lsPedido = servicioRestaurante.listarPedido();

        int id = lsPedido.get(lsPedido.size() - 1).getPed_Id();
        return id;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAplicacion;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRealizarPed;
    private javax.swing.JLabel jLableIMGPlato;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblImgPrincipal;
    private javax.swing.JLabel lblMensAplicacion;
    private javax.swing.JLabel lblRePed;
    private javax.swing.JLabel lblSf;
    private javax.swing.JPanel pnlRealizarPed;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
